import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex justify-center gap-8 py-6 border-b mb-8">
          <a href="/" className="font-semibold hover:underline">Home</a>
          <a href="/travelers" className="font-semibold hover:underline">Travelers</a>
          <a href="/map" className="font-semibold hover:underline">Map</a>
          <a href="/hotels" className="font-semibold hover:underline">Hotels</a>
          <a href="/travel-times" className="font-semibold hover:underline">Travel Times</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
